spring:
  application:
    name: private-proyect
  datasource:
    url: jdbc:postgresql://interchange.proxy.rlwy.net:39635/railway
    username: postgres
    password: QwkTGEAcCIAEEyEgNmboIBSDGqjDNZBe
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 8640000000

